=== kneem/hardcore-automation-system/HAS/src/com/hardcoresoft/has/datastorage/user.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/user" xmlns:tns="http://www.example.org/user" elementFormDefault="qualified">

    <element name="firstName" type="string"></element>

    <element name="lastName" type="string"></element>

    <element name="userName" type="string"></element>

    <element name="password" type="string"></element>

    <element name="permission" type="int"></element>
    

    <complexType name="users">
    	<sequence>
    		<element name="user" type="tns:user" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <complexType name="user">
    	<sequence>
    		<element ref="tns:firstName"></element>
    		<element ref="tns:lastName"></element>
    		<element ref="tns:userName"></element>
    		<element ref="tns:password"></element>
    		<element ref="tns:permission"></element>
    	</sequence>
    </complexType>


    <element name="users" type="tns:users"></element>
</schema>

=== kneem/hardcore-automation-system/HAS/tomcat7/webapps/HAS/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:users xmlns:tns="http://www.example.org/user"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/user user.xsd ">
    <tns:user>
        <tns:firstName>Michael</tns:firstName>
        <tns:lastName>Bieniek</tns:lastName>
        <tns:userName>mbieniek</tns:userName>
        <tns:password>kartofel</tns:password>
        <tns:permission>1</tns:permission>
    </tns:user>
    <tns:user>
        <tns:firstName>James</tns:firstName>
        <tns:lastName>Thomson</tns:lastName>
        <tns:userName>jomsie</tns:userName>
        <tns:password>test</tns:password>
        <tns:permission>0</tns:permission>
    </tns:user>
    <tns:user>
        <tns:firstName>Andrei</tns:firstName>
        <tns:lastName>Tulai</tns:lastName>
        <tns:userName>atulai</tns:userName>
        <tns:password>test</tns:password>
        <tns:permission>0</tns:permission>
    </tns:user>
</tns:users>
